MVC ASP/WebApplication1/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.BL;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class DevicesController : Controller
    {
        // GET: Devices
        public ActionResult Index()
        {


            #region For test

            var random = new Random();

            MvcApplication.Snmp.Devices.Add(new PrintedDevice() { Naim = "1", Description = "dasd", Location = "ds1ad", Ip = new SnmpSharpNet.IpAddress("10.10.0.1"), TonerCurrent = random.Next(10, 1000), TonerMax = 1000, PrintedPages = random.Next(50000) });
            MvcApplication.Snmp.Devices.Add(new PrintedDevice() { Naim = "2", Description = "dasd1", Location = "d2sad", Ip = new SnmpSharpNet.IpAddress("10.10.0.2"), TonerCurrent = random.Next(10, 1000), TonerMax = 1000, PrintedPages = random.Next(50000) });
            MvcApplication.Snmp.Devices.Add(new PrintedDevice() { Naim = "3", Description = "dasd2", Location = "d3sad", Ip = new SnmpSharpNet.IpAddress("10.10.0.3"), TonerCurrent = random.Next(10, 1000), TonerMax = 1000, PrintedPages = random.Next(50000) });
            MvcApplication.Snmp.Devices.Add(new PrintedDevice() { Naim = "4", Description = "dasd3", Location = "d4sad", Ip = new SnmpSharpNet.IpAddress("10.10.0.4"), TonerCurrent = random.Next(10, 1000), TonerMax = 1000, PrintedPages = random.Next(50000) });
            MvcApplication.Snmp.Devices.Add(new PrintedDevice() { Naim = "5", Description = "dasd4", Location = "d5sad", Ip = new SnmpSharpNet.IpAddress("10.10.0.5"), TonerCurrent = random.Next(10, 1000), TonerMax = 1000, PrintedPages = random.Next(50000) });
            MvcApplication.Snmp.Devices.Add(new PrintedDevice() { Naim = "6", Description = "dasd5", Location = "d2sad", Ip = new SnmpSharpNet.IpAddress("10.10.0.6"), TonerCurrent = random.Next(10, 1000), TonerMax = 1000, PrintedPages = random.Next(50000) });

            #endregion

            var list = MvcApplication.Snmp.Devices;

            ViewBag.TestList = (List<PrintedDevice>)list;

            return View();
        }

        [HttpPost]
        public ActionResult ScanForm(ScanerInfo model)
        {

            try
            {

                if (ModelState.IsValid)
                {
                    MvcApplication.Snmp.StartScan(new SnmpSharpNet.IpAddress(model.Ip1), new SnmpSharpNet.IpAddress(model.Ip1));
                    return Index();
                }
                return RedirectToAction("", model);

            }
            catch(Exception)
            {
                return RedirectToAction("", model);
            }

        }
    }
}

MVC ASP/WebApplication1/Views/Devices/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/CSS/Layout.css">
<link rel="stylesheet" href="~/CSS/Сommon.css">
<link rel="stylesheet" href="~/CSS/ipInput.css">
<link rel="stylesheet" href="~/CSS/ipInput.min.css">

<div>
    <div class="adress">
        <div class="last__section">



            <div display="inline">




                @model ScanerInfo

                @using (Html.BeginForm("ScanForm", "Devices", FormMethod.Post, new { @class = "ScanForm" }))
                {


                    <div class="cont_1">
                        Початкова адреса
                        @*<div class="ipt1" hidden="hidden"><span>@Html.TextBoxFor(m => m.Ip1)</span></div>*@
                        <div id="ip1"><div class="ip-input-container"><input type="text" class="ip-input-item" value=""><i class="ip-input-dot"></i><input type="text" class="ip-input-item" value=""><i class="ip-input-dot"></i><input type="text" class="ip-input-item" value=""><i class="ip-input-dot"></i><input type="text" class="ip-input-item" value=""></div></div>
                    </div>


                    <div class="cont_1">
                        Кінцева адреса
                        <div id="ip2"><div class="ip-input-container"><input type="text" class="ip-input-item" value=""><i class="ip-input-dot"></i><input type="text" class="ip-input-item" value=""><i class="ip-input-dot"></i><input type="text" class="ip-input-item" value=""><i class="ip-input-dot"></i><input type="text" class="ip-input-item" value=""></div></div>
                    </div>


                    @*<span>@Html.TextBoxFor(m => m.Ip1)</span>


            <span>@Html.TextBoxFor(m => m.Ip2)</span>*@

                    <input type="submit" value="Сканувати" />


                }
               

            </div>

        </div>
    </div>


    <div class="table_board">
        <table style="width:100%;" border="1">
            <tr>
                <th>Найменування</th>
                <th>IP адреса</th>

            </tr>
            @foreach (var i in ViewBag.TestList)
            {
                <tr><td>@i.Naim</td><td>@i.Ip.ToString()</td><td><button>Видалити</button></td></tr>
            }
        </table>

    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.slim.min.js"></script>
<script src="~/Scripts/ipInput.js"></script>

<script>var ipInput = $('#ip1').ipInput();</script>
<script>var ipInput = $('#ip2').ipInput();</script>


<script>
    $('#button').on('click', function () {
        $('#ipt1').text(ipInput.getIp());
        $('#ipt2').text(ipInput.getIp());
    })
</script>
@*<script>
    $('#button').on('click', function () {
        
    })
</script>*@